import Link from 'next/link';

const festivals = [
  { name: 'Butter Festival · Anduri Utsav', season: 'Usually late summer · Raithal & Dayara region', trek: 'dayara-bugyal', trekName: 'Dayara Bugyal', image: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1000&q=85', description: 'A community celebration associated with the shepherding villages around Dayara Bugyal. Visitors may encounter local food, folk traditions and a joyful butter-and-milk celebration. Festival plans and access vary by year, so confirm dates with local hosts before arranging travel.' },
  { name: 'Phool Dei', season: 'Spring · Villages across Uttarakhand', trek: 'nag-tibba', trekName: 'Nag Tibba', image: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1000&q=85', description: 'Welcome spring with this Kumaoni and Garhwali tradition in which children decorate doorsteps with flowers and offer seasonal greetings. Pair a village visit with a gentle mountain escape, travel respectfully, and ask locally before photographing ceremonies or homes.' },
  { name: 'Harela', season: 'Monsoon season · Kumaon and Garhwal', trek: 'kuari-pass', trekName: 'Kuari Pass', image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1000&q=85', description: 'Harela welcomes the rains and celebrates greenery, harvest and new beginnings. Communities mark the occasion with planted seedlings and family traditions. Monsoon trails can be wet or disrupted, so treat the festival as a cultural visit and choose trekking dates only after checking current route conditions.' },
  { name: 'Nanda Devi Raj Jat', season: 'A multi-day pilgrimage held periodically', trek: 'valley-of-flowers', trekName: 'Valley of Flowers', image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=85', description: 'This significant Himalayan pilgrimage follows a demanding route through sacred landscapes and remote settlements. It is held periodically rather than every year, and participation requires careful planning, respect for local customs and current official guidance. It is not a casual add-on to a standard trek.' },
  { name: 'Uttarayani Fair', season: 'January · Bageshwar and Kumaon', trek: 'dayara-bugyal', trekName: 'Dayara Bugyal', image: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1000&q=85', description: 'A winter gathering rooted in Kumaoni culture, with local markets, music and community traditions around the Makar Sankranti period. Explore the fair with local guides, then plan a separate mountain trip suited to winter weather and your experience level.' },
];

export default function FestivalsPage() {
  return <><section className="detail-hero"><div className="container"><span className="tag">Culture & mountain journeys</span><h1 className="title">Festivals of the Himalayas.</h1><p style={{maxWidth:650,fontSize:'1.1rem',color:'#fff'}}>Meet Uttarakhand through its seasons, village traditions and trails. Start with a festival, then find a trek that fits your time and experience.</p></div></section><section className="section"><div className="container"><div className="notice" style={{marginBottom:26}}>Festival dates, access and local arrangements can change. Confirm current details with local organizers, and plan trekking separately around weather and trail conditions.</div><div className="grid grid-3">{festivals.map(f=><article className="card" key={f.name}><img className="trek-img" src={f.image} alt="Himalayan landscape"/><div className="pad"><span className="eyebrow">{f.season}</span><h2>{f.name}</h2><p className="muted">{f.description}</p><p><b>Suggested trek:</b> {f.trekName}</p><div className="row" style={{marginTop:16}}><Link className="btn btn-outline" href={`/treks/${f.trek}`}>Trek details</Link><Link className="btn btn-dark" href={`/booking?trek=${f.trek}`}>Book trek</Link></div></div></article>)}</div><div className="card pad" style={{marginTop:30}}><span className="eyebrow">Beyond Uttarakhand</span><h2 className="section-title">Take your next journey to Nepal.</h2><p className="muted">Explore Himalayan routes in Nepal, from the classic Everest Base Camp journey to the Annapurna Sanctuary and quieter Mardi Himal ridges.</p><Link className="btn btn-dark" href="/treks?region=Nepal">Explore Nepal treks</Link></div></div></section></>;
}
